//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;

    public partial class CT_PHIEUNHAPHANG : BaseViewModel
    {
        private string _maPhieuNhapHang;
        public string MaPhieuNhapHang
        {
            get { return _maPhieuNhapHang; }
            set { _maPhieuNhapHang = value; OnPropertyChanged(); }
        }

        private string _maHangHoa;
        public string MaHangHoa
        {
            get { return _maHangHoa; }
            set { _maHangHoa = value; OnPropertyChanged(); }
        }

        private short? _soLuong;
        public short? SoLuong
        {
            get { return _soLuong; }
            set { _soLuong = value; OnPropertyChanged(); }
        }

        private int? _donGia;
        public int? DonGia
        {
            get { return _donGia; }
            set { _donGia = value; OnPropertyChanged(); }
        }

        private int? _thanhTien;
        public int? ThanhTien
        {
            get { return _thanhTien; }
            set { _thanhTien = value; OnPropertyChanged(); }
        }

        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
    }
}
