//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;

    public partial class LOAIPHONG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIPHONG()
        {
            this.PHONGs = new HashSet<PHONG>();
            this.THONGKEs = new HashSet<THONGKE>();
        }

        private string _maLoaiPhong;
        public string MaLoaiPhong
        {
            get { return _maLoaiPhong; }
            set { _maLoaiPhong = value; OnPropertyChanged(); }
        }

        private string _tenLoaiPhong;
        public string TenLoaiPhong
        {
            get { return _tenLoaiPhong; }
            set { _tenLoaiPhong = value; OnPropertyChanged(); }
        }

        private int? _donGia;
        public int? DonGia
        {
            get { return _donGia; }
            set { _donGia = value; OnPropertyChanged(); }
        }

        private string _trangThai;
        public string TrangThai
        {
            get { return _trangThai; }
            set { _trangThai = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGKE> THONGKEs { get; set; }
    }
}
