//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;

    public partial class PHIEUNHAPHANG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAPHANG()
        {
            this.CT_PHIEUNHAPHANG = new HashSet<CT_PHIEUNHAPHANG>();
        }

        private string _maPhieuNhapHang;
        public string MaPhieuNhapHang
        {
            get { return _maPhieuNhapHang; }
            set { _maPhieuNhapHang = value; OnPropertyChanged(); }
        }

        private string _maNhanVien;
        public string MaNhanVien
        {
            get { return _maNhanVien; }
            set { _maNhanVien = value; OnPropertyChanged(); }
        }

        private DateTime? _ngayLap;
        public DateTime? NgayLap
        {
            get { return _ngayLap; }
            set { _ngayLap = value; OnPropertyChanged(); }
        }

        private int? _triGia;
        public int? TriGia
        {
            get { return _triGia; }
            set { _triGia = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAPHANG> CT_PHIEUNHAPHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
